# 项目：整理Netflix电影演员评分数据

## 分析目标

此数据分析的目的是，整理不同流派影视作品，比如喜剧片、动作片、科幻片中，各演员出演作品的平均IMDB评分，从而挖掘出各个流派中的高评分作品演员。

本实战项目的目的在于练习整理数据，从而得到可供下一步分析的数据。

## 简介

原始数据集记录了截止至2022年7月美国地区可观看的所有Netflix电视剧及电影数据。数据集包含两个数据表：`titles.csv`和`credits.csv`。

`titles.csv`包含电影及电视剧相关信息，包括影视作品ID、标题、类型、描述、流派、IMDB（一个国外的在线评分网站）评分，等等。`credits.csv`包含超过7万名出现在Netflix影视作品的导演及演员信息，包括名字、影视作品ID、人物名、演职员类型（导演/演员）等。

`titles.csv`每列的含义如下：
- id：影视作品ID。
- title：影视作品标题。
- show_type：作品类型，电视节目或电影。
- description：简短描述。
- release_year：发布年份。
- age_certification：适龄认证。
- runtime：每集电视剧或电影的长度。
- genres：流派类型列表。
- production_countries：出品国家列表。
- seasons：如果是电视剧，则是季数。
- imdb_id：IMDB的ID。
- imdb_score：IMDB的评分。
- imdb_votes：IMDB的投票数。
- tmdb_popularity：TMDB的流行度。
- tmdb_score：TMDB的评分。

`credits.csv`每列的含义如下：
- person_ID：演职员ID。
- id：参与的影视作品ID。
- name：姓名。
- character_name：角色姓名。
- role：演职员类型，演员或导演。

In [1]:
import pandas as pd

In [2]:
titles = pd.read_csv("titles.csv")
credits = pd.read_csv("credits.csv")

In [3]:
titles

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5845,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.8,45.0,1.466,NaN
5846,tm898842,C/O Kaadhal,MOVIE,A heart warming film that explores the concept...,2021,NaN,134,['drama'],[],NaN,tt11803618,7.7,348.0,NaN,NaN
5847,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300
5848,tm1035612,Dad Stop Embarrassing Me - The Afterparty,MOVIE,"Jamie Foxx, David Alan Grier and more from the...",2021,PG-13,37,[],['US'],NaN,NaN,NaN,NaN,1.296,10.000
5849,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,7,"['family', 'animation', 'comedy']",[],1.0,tt13711094,7.8,18.0,2.289,10.000

In [4]:
credits

,person_id,id,name,character,role
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR
2,7064,tm84618,Albert Brooks,Tom,ACTOR
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...
77796,736339,tm1059008,Adelaida Buscato,María Paz,ACTOR
77797,399499,tm1059008,Luz Stella Luengas,Karen Bayona,ACTOR
77798,373198,tm1059008,Inés Prieto,Fanny,ACTOR
77799,378132,tm1059008,Isabel Gaona,Cacica,ACTOR
77800,1950416,tm1059008,Julian Gaviria,NaN,DIRECTOR

In [5]:
Actors_Rating = pd.merge(titles, credits, on="id")
Actors_Rating

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,3748,Robert De Niro,Travis Bickle,ACTOR
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,14658,Jodie Foster,Iris Steensma,ACTOR
2,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,7064,Albert Brooks,Tom,ACTOR
3,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,3739,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179,48933,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77796,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,736339,Adelaida Buscato,María Paz,ACTOR
77797,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,399499,Luz Stella Luengas,Karen Bayona,ACTOR
77798,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,373198,Inés Prieto,Fanny,ACTOR
77799,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,378132,Isabel Gaona,Cacica,ACTOR
77800,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300,1950416,Julian Gaviria,NaN,DIRECTOR

In [6]:
# 接下来进行一些必要的清洗工作
Actors_Rating["role"].value_counts()

role
ACTOR       73251
DIRECTOR     4550
Name: count, dtype: int64

In [7]:
# 挑选实际需要的数据——裁剪
Actors_Rating_Cleaned = Actors_Rating[["title", "genres", "imdb_score", "imdb_votes", "name", "role"]]
Actors_Rating_Cleaned = Actors_Rating_Cleaned[Actors_Rating_Cleaned["role"] == "ACTOR"]
Actors_Rating_Cleaned

,title,genres,imdb_score,imdb_votes,name,role
0,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Robert De Niro,ACTOR
1,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Jodie Foster,ACTOR
2,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Albert Brooks,ACTOR
3,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Harvey Keitel,ACTOR
4,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Cybill Shepherd,ACTOR
...,...,...,...,...,...,...
77795,Lokillo,['comedy'],3.8,68.0,Aída Morales,ACTOR
77796,Lokillo,['comedy'],3.8,68.0,Adelaida Buscato,ACTOR
77797,Lokillo,['comedy'],3.8,68.0,Luz Stella Luengas,ACTOR
77798,Lokillo,['comedy'],3.8,68.0,Inés Prieto,ACTOR
77799,Lokillo,['comedy'],3.8,68.0,Isabel Gaona,ACTOR

In [8]:
Actors_Rating_Cleaned = Actors_Rating_Cleaned.explode('genres')
Actors_Rating_Cleaned

,title,genres,imdb_score,imdb_votes,name,role
0,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Robert De Niro,ACTOR
1,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Jodie Foster,ACTOR
2,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Albert Brooks,ACTOR
3,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Harvey Keitel,ACTOR
4,Taxi Driver,"['drama', 'crime']",8.2,808582.0,Cybill Shepherd,ACTOR
...,...,...,...,...,...,...
77795,Lokillo,['comedy'],3.8,68.0,Aída Morales,ACTOR
77796,Lokillo,['comedy'],3.8,68.0,Adelaida Buscato,ACTOR
77797,Lokillo,['comedy'],3.8,68.0,Luz Stella Luengas,ACTOR
77798,Lokillo,['comedy'],3.8,68.0,Inés Prieto,ACTOR
77799,Lokillo,['comedy'],3.8,68.0,Isabel Gaona,ACTOR

In [10]:
# 将 genres 列转换为实际的 Series
Actors_Rating_Cleaned["genres"] = Actors_Rating_Cleaned["genres"].str.replace("["," ")
Actors_Rating_Cleaned["genres"] = Actors_Rating_Cleaned["genres"].str.replace("'"," ")
Actors_Rating_Cleaned["genres"] = Actors_Rating_Cleaned["genres"].str.replace("]"," ")
Actors_Rating_Cleaned["genres"]
Actors_Rating_Cleaned["genres"].dtype

dtype('O')

In [11]:
genres_lists = Actors_Rating_Cleaned["genres"].str.split(",")
genres_lists

0        [  drama ,   crime  ]
1        [  drama ,   crime  ]
2        [  drama ,   crime  ]
3        [  drama ,   crime  ]
4        [  drama ,   crime  ]
                 ...
77795             [  comedy  ]
77796             [  comedy  ]
77797             [  comedy  ]
77798             [  comedy  ]
77799             [  comedy  ]
Name: genres, Length: 73251, dtype: object

In [12]:
Actors_Rating_Cleaned["genres"] = pd.Series(genres_lists)
Actors_Rating_Cleaned["genres"]

0        [  drama ,   crime  ]
1        [  drama ,   crime  ]
2        [  drama ,   crime  ]
3        [  drama ,   crime  ]
4        [  drama ,   crime  ]
                 ...
77795             [  comedy  ]
77796             [  comedy  ]
77797             [  comedy  ]
77798             [  comedy  ]
77799             [  comedy  ]
Name: genres, Length: 73251, dtype: object

In [13]:
Actors_Rating_Cleaned.dropna(subset = "imdb_score", inplace = True)
Actors_Rating_Cleaned

,title,genres,imdb_score,imdb_votes,name,role
0,Taxi Driver,"[ drama , crime ]",8.2,808582.0,Robert De Niro,ACTOR
1,Taxi Driver,"[ drama , crime ]",8.2,808582.0,Jodie Foster,ACTOR
2,Taxi Driver,"[ drama , crime ]",8.2,808582.0,Albert Brooks,ACTOR
3,Taxi Driver,"[ drama , crime ]",8.2,808582.0,Harvey Keitel,ACTOR
4,Taxi Driver,"[ drama , crime ]",8.2,808582.0,Cybill Shepherd,ACTOR
...,...,...,...,...,...,...
77795,Lokillo,[ comedy ],3.8,68.0,Aída Morales,ACTOR
77796,Lokillo,[ comedy ],3.8,68.0,Adelaida Buscato,ACTOR
77797,Lokillo,[ comedy ],3.8,68.0,Luz Stella Luengas,ACTOR
77798,Lokillo,[ comedy ],3.8,68.0,Inés Prieto,ACTOR
77799,Lokillo,[ comedy ],3.8,68.0,Isabel Gaona,ACTOR

In [14]:
Actors_Rating_Cleaned["role"].isnull().sum()

np.int64(0)

In [15]:
Actors_Rating_Modify = Actors_Rating_Cleaned.explode("genres")
Actors_Rating_Modify

,title,genres,imdb_score,imdb_votes,name,role
0,Taxi Driver,drama,8.2,808582.0,Robert De Niro,ACTOR
0,Taxi Driver,crime,8.2,808582.0,Robert De Niro,ACTOR
1,Taxi Driver,drama,8.2,808582.0,Jodie Foster,ACTOR
1,Taxi Driver,crime,8.2,808582.0,Jodie Foster,ACTOR
2,Taxi Driver,drama,8.2,808582.0,Albert Brooks,ACTOR
...,...,...,...,...,...,...
77795,Lokillo,comedy,3.8,68.0,Aída Morales,ACTOR
77796,Lokillo,comedy,3.8,68.0,Adelaida Buscato,ACTOR
77797,Lokillo,comedy,3.8,68.0,Luz Stella Luengas,ACTOR
77798,Lokillo,comedy,3.8,68.0,Inés Prieto,ACTOR
77799,Lokillo,comedy,3.8,68.0,Isabel Gaona,ACTOR

In [16]:
Actors_Rating_Modify["genres"] = Actors_Rating_Modify["genres"].astype("str")
Actors_Rating_Modify["genres"]

0            drama
0           crime
1            drama
1           crime
2            drama
            ...
77795      comedy
77796      comedy
77797      comedy
77798      comedy
77799      comedy
Name: genres, Length: 205443, dtype: object

In [17]:
Actors_Rating_Modify["genres"].value_counts()

genres
drama              31086
comedy             19710
thriller           14772
action             14561
drama              12946
crime              10135
comedy              9176
romance             7994
romance             6909
european            6887
scifi               6165
fantasy             6095
thriller            5977
animation           4970
crime               4849
family              4814
action              4664
horror              4093
history             2940
documentation       2767
fantasy             2650
documentation       2628
family              2549
war                 2027
music               1829
history             1761
sport               1673
horror              1648
scifi               1405
music               1403
war                 1041
animation            830
sport                730
western              669
reality              429
western              257
reality              209
european             193
                       2
Name: count, dtype: int64

In [18]:
Actors_Rating_Modify["genres"] = Actors_Rating_Modify["genres"].str.strip().str.lower()

In [19]:
Actors_Rating_Modify = Actors_Rating_Modify[Actors_Rating_Modify["genres"] !=""]
Actors_Rating_Modify

             title  genres  imdb_score  imdb_votes                name   role
0      Taxi Driver   drama         8.2    808582.0      Robert De Niro  ACTOR
0      Taxi Driver   crime         8.2    808582.0      Robert De Niro  ACTOR
1      Taxi Driver   drama         8.2    808582.0        Jodie Foster  ACTOR
1      Taxi Driver   crime         8.2    808582.0        Jodie Foster  ACTOR
2      Taxi Driver   drama         8.2    808582.0       Albert Brooks  ACTOR
...            ...     ...         ...         ...                 ...    ...
77795      Lokillo  comedy         3.8        68.0        Aída Morales  ACTOR
77796      Lokillo  comedy         3.8        68.0    Adelaida Buscato  ACTOR
77797      Lokillo  comedy         3.8        68.0  Luz Stella Luengas  ACTOR
77798      Lokillo  comedy         3.8        68.0         Inés Prieto  ACTOR
77799      Lokillo  comedy         3.8        68.0        Isabel Gaona  ACTOR

[205441 rows x 6 columns]

In [20]:
Actors_Rating_Modify.info()

<class 'pandas.core.frame.DataFrame'>
Index: 205441 entries, 0 to 77799
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   title       205441 non-null  object
 1   genres      205441 non-null  object
 2   imdb_score  205441 non-null  float64
 3   imdb_votes  205309 non-null  float64
 4   name        205441 non-null  object
 5   role        205441 non-null  object
dtypes: float64(2), object(4)
memory usage: 11.0+ MB

In [21]:
Actors_Rating_Modify["genres"].value_counts()

genres
drama            44032
comedy           28886
thriller         20749
action           19225
crime            14984
romance          14903
fantasy           8745
scifi             7570
family            7363
european          7080
animation         5800
horror            5741
documentation     5395
history           4701
music             3232
war               3068
sport             2403
western            926
reality            638
Name: count, dtype: int64

In [22]:
# 开始计量每个演员在各种电影类型中的表现
Actors_ranking = Actors_Rating_Modify.groupby(["genres","name"])[["imdb_score"]].mean()
Actors_ranking

                            imdb_score
genres  name
action  50 Cent                    7.0
        A. C. Murali Mohan         7.5
        A.J. Bernardo              2.6
        A.J. LoCascio              6.5
        A.K. Hangal                6.6
...                                ...
western Zoe Kazan                  7.3
        Zoë Bell                   8.1
        Álvaro Flores              6.1
        Óscar Jaenada              6.1
        Úrsula Murayama            6.1

[168593 rows x 1 columns]

In [23]:
# pd.pivot_table(Actors_Rating_Modify, index=["genres", "name", "title"], value = "imdb_score", aggfunc = np.mean )

In [24]:
Actors_highest = Actors_ranking.groupby(["genres"])[["imdb_score"]].max()
Actors_highest

               imdb_score
genres
action                9.3
animation             9.3
comedy                9.2
crime                 9.5
documentation         9.1
drama                 9.5
european              8.9
family                9.3
fantasy               9.3
history               9.1
horror                9.0
music                 8.8
reality               8.9
romance               9.2
scifi                 9.3
sport                 9.1
thriller              9.5
war                   8.8
western               8.9

In [28]:
ActorsRanking = pd.merge(Actors_highest,Actors_Rating_Modify,on=["genres","imdb_score"])
ActorsRanking

,genres,imdb_score,title,imdb_votes,name,role
0,action,9.3,Avatar: The Last Airbender,303666.0,Zach Tyler,ACTOR
1,action,9.3,Avatar: The Last Airbender,303666.0,Mae Whitman,ACTOR
2,action,9.3,Avatar: The Last Airbender,303666.0,Jack De Sena,ACTOR
3,action,9.3,Avatar: The Last Airbender,303666.0,Dante Basco,ACTOR
4,action,9.3,Avatar: The Last Airbender,303666.0,Jessie Flower,ACTOR
...,...,...,...,...,...,...
202,war,8.8,Vinland Saga,32535.0,Akio Otsuka,ACTOR
203,western,8.9,Cowboy Bebop,115448.0,Koichi Yamadera,ACTOR
204,western,8.9,Cowboy Bebop,115448.0,Unsho Ishizuka,ACTOR
205,western,8.9,Cowboy Bebop,115448.0,Megumi Hayashibara,ACTOR
206,western,8.9,Cowboy Bebop,115448.0,Aoi Tada,ACTOR

In [29]:
ActorsRanking.to_csv("ActorsRanking.csv")

In [30]:
Actors_Rating_Cleaned[Actors_Rating_Cleaned["name"] == "Dante Basco"]

,title,genres,imdb_score,imdb_votes,name,role
4875,Avatar: The Last Airbender,"[ scifi , animation , action , family ,...",9.3,303666.0,Dante Basco,ACTOR
7925,Blood and Bone,"[ thriller , sport , action , crime , ...",6.7,33051.0,Dante Basco,ACTOR